### ISSUE TITLE
Running devtools::test() twice in a row results in hang

### ISSUE THREAD

**Issue by nbarlowATI** [tgve/tgver#27]
Running the command `devtools::test()` from an R or RStudio console in the "tgver/" directory, the suite of (currently 48) tests runs to completion.

However, running the same command again, we get the following output:
```
> devtools::test()
ℹ Loading tgver
ℹ Testing tgver
✓ | F W S  OK | Context
x | 2       6 | build [1.5s]                                                                       
───────────────────────────────────────────────────────────────────────────────────────────────────
Failure (test-build.R:12:3): build works
any(g) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

Failure (test-build.R:13:3): build works
any(g2) is not TRUE

`actual`:   FALSE
`expected`: TRUE 
───────────────────────────────────────────────────────────────────────────────────────────────────
⠏ |         0 | explore_dir                                                                        More than one matching columns found between the two files
                    using the first matchin column as `geographyColumn` value.
http://127.0.0.1:8000/data.csv http://127.0.0.1:8000/geoURL police_forceServing data from http://127.0.0.1:8000/data.csv
Serving geography from: http://127.0.0.1:8000/geoURL
Running plumber API at http://127.0.0.1:8000
```
and it hangs indefinitely.

**Comment by layik** [comment]
Hi @nbarlowATI, please check if you have pulled the latest of the package. I just checked and as I expected "master" should not have `test-build.R` any longer (since last night).

https://github.com/tgve/tgver/tree/master/tests/testthat

**Comment by nbarlowATI** [comment]
Hi @layik , ah thanks, you're right - I hadn't pulled the latest changes.
Doing that, I now see 42 tests that all pass.
However, the same thing happens when I run `devtools::test()` immediately again - it still hangs after the message ```Running plumber API at http://127.0.0.1:8000```.

**Comment by layik** [comment]
Will check this thank you @nbarlowATI

**Comment by layik** [comment]
Thank you again @nbarlowATI for picking this up. There is better way of unit testing with `testthat` but cleaning up afterwards is as good. In at least two cases, I was not doing cleaning up as you can see in the commit above. Therefore, when the second test runs in the same R "environment" or session, the expected behaviour was not in place therefore a thread would be opened unintentionally.

Here is a redacted but reproducible code as the change has been pushed.

``` r
system("git clone https://github.com/tgve/tgver")
devtools::test(pkg = "tgver")
#> Warning: replacing previous import 'lifecycle::last_warnings' by
#> 'rlang::last_warnings' when loading 'tibble'
#> Warning: replacing previous import 'lifecycle::last_warnings' by
#> 'rlang::last_warnings' when loading 'pillar'
#> ℹ Loading tgver
#> ℹ Testing tgver
...........
...........
#> ══ Results ══════════════════════════════════════
#> Duration: 7.7 s
#> 
#> [ FAIL 0 | WARN 0 | SKIP 0 | PASS 42 ]
devtools::test(pkg = "tgver")
#> ℹ Loading tgver
#> ℹ Testing tgver
...........
...........
#> ══ Results ══════════════════════════════════════
#> Duration: 8.5 s
#> 
#> [ FAIL 0 | WARN 0 | SKIP 0 | PASS 42 ]
```

<sup>Created on 2022-02-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details>
<summary>
session info
</summary>
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

</details>

**Comment by layik** [comment]
@nbarlowATI please feel free to close this ticket if your local tests pass on master too as per above.

**Comment by nbarlowATI** [comment]
Excellent, many thanks @layik , I can confirm that this is fixed now on master, dev, and our working branch.  Closing now...
